### ISSUE TITLE
Symbols not showing

### ISSUE THREAD

**Issue by Emile-ajar** [jefdongus/insert-symbols-anki-addon#1]
Hey, 

I wrote on the Ankiweb page that symbols are not showing for me. 

As requested:
1) Version 2.1.15 (442df9d6)
Qt 5.12.1 PyQt 5.11.3

2) Windows 10 pro (latest update)

3) English (UK)

4) 
![image](https://user-images.githubusercontent.com/53612974/66814643-9d25f780-ef3f-11e9-9d05-7b682e824cf6.png)

5) All symbols. 

I went through my entire list of add-ons and disabled each of them one-by-one. I found, interestingly, that the **Frozen Fields** add-on appears to be the cause of the issue. When it is disabled, Symbols As You Type works. 

Please let me know if there is any more information I can provide and thank you for this great add-on, I hope to get it working :)

**Comment by Emile-ajar** [comment]
I have also checked if the "Remember last input when adding" option in Note Types --> Fields --> Options evokes the same issue and it does not.

**Comment by jefdongus** [comment]
Thanks for doing all that digging! Turns out this was a conflict between this plugin and Frozen Fields. Frozen Fields replaces one of the default card editor functions with a custom one, which meant that the code to check for symbol replacements was no longer running, as this plugin's code was attached to that default function.

I made some changes to make this plugin less vulnerable to these types of issues. Please update to the latest version and see if this still a problem!
