### ISSUE TITLE
Not working with latest Anki 2.1.41beta2

### ISSUE THREAD

**Issue by AnKingMed** [jefdongus/insert-symbols-anki-addon#21]
This is causing multiple errors with the latest beta when trying to open the browser. Happy to help troubleshoot and test any fixes.  It seems this is a very popular add-on because many people are sad it's not working.

**Comment by DarcyMur** [comment]
This is also occurring with the 2.1.41 release version.
Here's the error message that Anki spits out when i go into browsing screen.

Thank you so much for this addon btw!

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.41 (312fa278) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-07 11:52:41

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1067, in onBrowse
  File "aqt\__init__.py", line 101, in open
  File "<decorator-gen-34>", line 2, in __init__
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 81, in repl
TypeError: on_browser_init() takes 3 positional arguments but 5 were given

**Comment by kleinerpirat** [comment]
@hgiesel Care to take a look at it to judge whether it's an easy fix or not? It's a very useful and popular add-on, but it seems like the author @jefdongus isn't active atm.
The code is commented very nicely.

Fixing the symbol insertion isn't trivial to me, but i got a feeling it could be for you.
The add-on uses `replacer.js` to perform symbol replacement. The import is working, since it throws errors when I break things (deliberately, of course ;D).

**Comment by jefdongus** [comment]
Should be working when adding cards/editing cards in the card browser (inserting symbols into the card browser search bar is not working yet).
