### ISSUE TITLE
Major Issue: Symbols Within Words

### ISSUE THREAD

**Issue by herotozero** [jefdongus/insert-symbols-anki-addon#37]
The add on does not work if symbols occur **inside** of a word, for example:

I want "oe" to be replaced by "ö" to write the German word "Löffel". Typing "Loeffel" however will not be modified by the addon. I have to type "L oe ffel", which results in "L ö ffel" and then manually remove the whitespaces.

Could you please add support so that "oe" will be picked up by the addon, even if it is inside of a word. I think this small change can make this a lot more useful for many users.

Thank you so much.

**Comment by jefdongus** [comment]
Hm, the plugin is designed so that most keys are enclosed in `::` (see below for some default symbols). There are a few exceptions for arrows for convenience, but those are exceptions rather than the norm.
![image](https://user-images.githubusercontent.com/6502895/172530589-aed884f8-478b-48b9-bf2a-ba908e954878.png)

What you're describing should work if you set up the key as `:oe:`... then as soon as you type `L:oe:` it should change to "Lö".
