### ISSUE TITLE
Not working in anki 23.10

### ISSUE THREAD

**Issue by orangelover12** [jefdongus/insert-symbols-anki-addon#45]
Hello!
First of all, I really like this add-on and I would like to thank you.
My issue is that ANKI 23.10 version came out today and this addon does not work.
I would really appreciate it if you could update it.
Have a good day!

**Comment by NameLessGO** [comment]
Why u referring to anki as 2.1.10 and not 23.10? not only here but in others add-on repos as well?

https://github.com/ankitects/anki/releases

**Comment by orangelover12** [comment]
It was a typo. I wrote that it was updated today. You could probably tell from the context that it wasn't 2.1.10. The reason I left reports in several places was because many things were updated this time and many add-ons did not work.

**Comment by 75462565374252** [comment]
Please update it. It's one of the most important plugins for me.

**Comment by Jonhy75** [comment]
Hello
Same problem here with Anki 23.10.1
This plugin has not been updated since June 2022.
The problem comes from the fact that the addon uses qt5 and the new version of Anki only supports qt6.
Here is the addon updated by @zjosua that I 've packaged. 
You just need to unzip it and install it directly in addon menu in Anki.
[insert-symbol.ankiaddon.zip](https://github.com/jefdongus/insert-symbols-anki-addon/files/13328043/insert-symbol.ankiaddon.zip)

**Comment by jefdongus** [comment]
New version compatible with Anki 23.10
